version: '3.8'

services:
  livestream-link-monitor:
    container_name: livestream-monitor-test
    build: .
    env_file: ../.env.test
    environment:
      - NODE_ENV=test
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./test-credentials.json:/app/test-credentials.json:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M