services:
  livestream-monitor:
    build: .
    container_name: livestream-monitor
    restart: unless-stopped
    environment:
      # Discord Configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}

      # Twitch Configuration
      - TWITCH_CHANNEL=${TWITCH_CHANNEL}

      # Google Sheets Configuration
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json

      # Optional Configuration
      - CHECK_INTERVAL=${CHECK_INTERVAL:-60000}
      - MAX_CONCURRENT_CHECKS=${MAX_CONCURRENT_CHECKS:-3}
      - IGNORE_LIST_SYNC_INTERVAL=${IGNORE_LIST_SYNC_INTERVAL:-10000}
      
      # Rate limiting
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-10}
      
      # Browser pool
      - MAX_BROWSERS=${MAX_BROWSERS:-3}

      # Playwright Configuration
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./index.js:/app/index.js:ro
      - ./config.js:/app/config.js:ro
      - ./lib:/app/lib:ro

    # Security
    security_opt:
      - no-new-privileges:true

    # Resource limits (compose v3+ syntax)
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
          
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-x", "node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"