services:
  livestream-monitor:
    build: .
    container_name: livestream-monitor
    restart: unless-stopped
    init: true
    environment:
      # Discord Configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}

      # Twitch Configuration
      - TWITCH_CHANNEL=${TWITCH_CHANNEL}

      # StreamSource API Configuration
      - STREAMSOURCE_API_URL=${STREAMSOURCE_API_URL:-https://api.streamsource.com}
      - STREAMSOURCE_EMAIL=${STREAMSOURCE_EMAIL}
      - STREAMSOURCE_PASSWORD=${STREAMSOURCE_PASSWORD}

      # Optional Configuration
      - IGNORE_LIST_SYNC_INTERVAL=${IGNORE_LIST_SYNC_INTERVAL:-30000}
      - EXISTING_URLS_SYNC_INTERVAL=${EXISTING_URLS_SYNC_INTERVAL:-30000}
      - KNOWN_CITIES_SYNC_INTERVAL=${KNOWN_CITIES_SYNC_INTERVAL:-300000}

      # Rate limiting
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-10}

      # Other configuration (optional)
      - TIMEZONE=${TIMEZONE:-America/Los_Angeles}
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # Confirmation settings (optional)
      - DISCORD_CONFIRM_REACTION=${DISCORD_CONFIRM_REACTION:-true}
      - TWITCH_CONFIRM_REPLY=${TWITCH_CONFIRM_REPLY:-true}

    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./index.js:/app/index.js:ro
      - ./config.js:/app/config.js:ro
      - ./lib:/app/lib:ro

    # Security
    security_opt:
      - no-new-privileges:true

    # Resource limits (compose v3+ syntax)
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'

    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-x", "node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"